# Generated by Django 5.1 on 2025-11-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('model', 'Model'), ('dataset', 'Dataset'), ('code', 'Code')], max_length=16)),
                ('source_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'type', 'source_url')},
            },
        ),
    ]
