# Generated by Django 5.1 on 2025-11-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='blob',
            field=models.FileField(blank=True, upload_to='registry/raw/'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(blank=True, max_length=256, null=True)),
                ('code_name', models.CharField(blank=True, max_length=256, null=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modelinfo', to='api.artifact')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_using_code', to='api.artifact')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_using_dataset', to='api.artifact')),
            ],
        ),
    ]
