# Generated by Django 5.1 on 2025-12-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_usergroup_artifact_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='download_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='file_size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='net_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='rating_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='s3_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('rating', 'Rating'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
