# Generated by Django 5.1 on 2025-12-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_artifact_download_url_artifact_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='download_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
