# Generated by Django 5.1 on 2025-12-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_artifact_download_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('pending_rating', 'Pending Rating'), ('rating_in_progress', 'Rating In Progress'), ('disqualified', 'Disqualified'), ('ingesting', 'Ingesting Artifact'), ('ready', 'Ready'), ('failed', 'Failed'), ('pending', 'Pending'), ('downloading', 'Downloading'), ('rating', 'Rating'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('update', 'Update'), ('delete', 'Delete'), ('download', 'Download'), ('login', 'Login'), ('logout', 'Logout'), ('search', 'Search'), ('view', 'View'), ('rate', 'Rate')], db_index=True, max_length=20)),
                ('artifact_type', models.CharField(blank=True, choices=[('model', 'Model'), ('dataset', 'Dataset'), ('code', 'Code')], max_length=20, null=True)),
                ('artifact_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('artifact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activity_lo_timesta_cd2ed1_idx'), models.Index(fields=['user', '-timestamp'], name='activity_lo_user_579349_idx'), models.Index(fields=['action', '-timestamp'], name='activity_lo_action_f5c228_idx'), models.Index(fields=['artifact_type', '-timestamp'], name='activity_lo_artifac_691c6a_idx')],
            },
        ),
    ]
