"""
Django settings for registry project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if SECRET_KEY is None:
    if os.getenv("DJANGO_DEBUG", "1") == "1":  # dev fallback
        SECRET_KEY = "dev-not-secret"
    else:
        raise RuntimeError("DJANGO_SECRET_KEY is required in production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = []
hosts = os.getenv("ALLOWED_HOSTS")
if not hosts:
    raise RuntimeError("ALLOWED_HOSTS is required in production")
hosts = hosts.split(",")
for h in hosts:
    ALLOWED_HOSTS.append(h)
print("ALLOWED HOSTS: ")
for h in ALLOWED_HOSTS:
    print(h)
print("------------------")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Added apps
    "corsheaders",  # CORS support for frontend
    "rest_framework",
    "api",  # our app in backend/web/registry/api
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF disabled for API - using token-based auth instead
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'registry.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'registry.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Switch DB by env var. If POSTGRES_HOST is present -> use Postgres; else SQLite for dev.
postgres_host = os.getenv("POSTGRES_HOST")
if postgres_host:
    # Helper to strip accidental quotes from .env files
    def clean(val):
        return val.strip().strip("'").strip('"') if val else val

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": clean(os.getenv("POSTGRES_DB", "registry")),
            "USER": clean(os.getenv("POSTGRES_USER", "registry")),
            "PASSWORD": clean(os.getenv("POSTGRES_PASSWORD", "")),
            "HOST": clean(postgres_host),
            "PORT": clean(os.getenv("POSTGRES_PORT", "5432")),
            "OPTIONS": {
                # RDS usually supports TLS; "require" is a safe default
                "sslmode": clean(os.getenv("POSTGRES_SSLMODE", "require"))
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# DEV defaults
USE_S3 = bool(os.getenv("USE_S3", "false").lower() == "true")
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# PROD (set in env)
AWS_STORAGE_BUCKET_NAME = os.getenv("S3_BUCKET", "")
AWS_S3_REGION_NAME = os.getenv("AWS_REGION", "us-east-1")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# Allow frontend to make requests to backend
# Allow all localhost ports for development
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

CORS_ALLOW_CREDENTIALS = True

# Allow all methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow headers needed for authentication
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-authorization',
]

CORS_EXPOSE_HEADERS = [
    'x-authorization',
]
